[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
